openpype/lib/project_backpack.py
Automatic synchronization requires conflict resolution.
=> Fork Sync: Update from parent repository

.github/ISSUE_TEMPLATE/bug_report.yml, .github/workflows/sync_fork.yml
=> Bug report update

.github/ISSUE_TEMPLATE/bug_report.yml, .github/workflows/configuration.json, .github/workflows/sync_fork.yml, .github/workflows/update-deadline-plugin.yml
Revert code changes from local history dated before 7-10-23 at 4:12PM
=> Revert to 7-10-23 4:12PM

openpype/hosts/maya/plugins/create/create_rig.py, openpype/hosts/maya/plugins/publish/validate_rig_output_ids.py
Suggestions to improve https://github.com/ynput/OpenPype/pull/5310
=> Fix rig selection sets naming

openpype/style/data.json, openpype/style/style.css, openpype/tools/settings/settings/categories.py, openpype/tools/settings/settings/window.py
Paragraphs contain detailed information on the changes made to the product or service, providing an in-depth description of the updates and enhancements. They can be used to explain the reasoning behind the changes, or to highlight the importance of the new features. Paragraphs can often include links to further information or support documentation.
Paragraphs of text giving context of additional technical information or code examples.
1. start with this step
2. follow this step
=> feat: Add protect settings system

openpype/hosts/maya/plugins/publish/collect_instances.py, openpype/hosts/unreal/api/plugin.py, openpype/lib/local_settings.py, openpype/version.py
[HOTFIX: Fix condition to ensure password is requested](https://github.com/quadproduction/OpenPype/commit/8d8c76cba26b6abff949696254fdd53a6e00d02c)
[HOTFIX: Ensure instance metadata are properly parsed (dict)](https://github.com/quadproduction/OpenPype/commit/450029e3a1d1861b1dedb4b9015a31d5e56adf74)
=> Hotfix/3.15.12 quad.3.14.1

openpype/hosts/tvpaint/plugins/create/create_render.py, openpype/version.py
- https://github.com/quadproduction/issues/issues/198
=> Release 3.16.9-quad-1.4.0

openpype/hosts/nuke/plugins/load/load_effects.py
Connect the effect to the currently selected node or under the cursor position if selection is None
1. `git checkout bugfix/272-bug-nuke-effect-subsets-stick-to-the-wrong-node`
2. Go to TEST_OP2_PUB_23_7 > Shots > 902 > 902_0010, Compo Task, Launch Nuke
3. Select any node in the nodegraph
4. Open the Asset Loader via the openpype menu -> Load
5. Make sure your 'effect' filter is turned on in the bottom left corner
6. Load the EffectPlateScan with a right click -> Load effect (Nodes)
=> Change node connection logic when load_effects is applied

openpype/hosts/maya/plugins/publish/validate_frame_range.py, openpype/hosts/nuke/plugins/load/load_effects.py, openpype/modules/deadline/common/publish/collect_pools.py, openpype/modules/deadline/common/publish/submit_publish_job.py, openpype/modules/ftrack/event_handlers_user/action_prepare_project.py, openpype/modules/ftrack/ftrack_module.py, openpype/modules/ftrack/plugins/publish/integrate_ftrack_source_workfile.py, openpype/settings/defaults/project_settings/ftrack.json, openpype/settings/entities/schemas/projects_schema/schema_project_ftrack.json, openpype/settings/entities/schemas/projects_schema/schema_project_maya.json, openpype/settings/lib.py, openpype/version.py
- https://github.com/quadproduction/issues/issues/272
- https://github.com/quadproduction/issues/issues/275
- https://github.com/quadproduction/issues/issues/263
- https://github.com/quadproduction/issues/issues/209
- https://github.com/quadproduction/issues/issues/200
- https://github.com/quadproduction/issues/issues/257
=> Release 3.16.9-quad-1.5.0

.pre-commit-config.yaml, openpype/hosts/blender/hooks/pre_add_set_scene_properties.py, openpype/version.py
Paragraphs contain detailed information on the changes made to the product or service, providing an in-depth description of the updates and enhancements. They can be used to explain the reasoning behind the changes, or to highlight the importance of the new features. Paragraphs can often include links to further information or support documentation.
Paragraphs of text giving context of additional technical information or code examples.
1. start with this step
2. follow this step
=> Hotfix/3.16.9 quad 1.6.1

openpype/modules/deadline/common/publish/collect_pools.py, openpype/modules/deadline/maya/publish/submit_maya_deadline.py, openpype/modules/deadline/maya/publish/submit_maya_remote_publish_deadline.py, openpype/modules/deadline/nuke/publish/submit_nuke_deadline.py
This PR fix issues about Pools Management, Profile issues.
Also include some code cleanup.
=> Fix Deadline Pool and Profile issues

openpype/hosts/maya/plugins/publish/validate_frame_range.py
Update Default Value by including "include_handles_default"
=> [Maya] [ValidateFrameRange] Update Default Value

openpype/hosts/blender/blender_addon/addons/DeadlineBlenderScenePrepare.py, openpype/hosts/blender/blender_addon/addons/RenderPlayblast.py, openpype/hosts/blender/blender_addon/addons/libs/paths.py, openpype/modules/deadline/common/publish/collect_pools.py, openpype/modules/deadline/deadline_module.py, openpype/modules/deadline/maya/publish/submit_maya_deadline.py, openpype/modules/deadline/maya/publish/submit_maya_remote_publish_deadline.py, openpype/modules/deadline/nuke/publish/submit_nuke_deadline.py, openpype/modules/deadline/utils.py, openpype/settings/entities/enum_entity.py, openpype/version.py
- https://github.com/quadproduction/issues/issues/341
- https://github.com/quadproduction/issues/issues/323
=> Release/3.16.9 quad 1.8.1

openpype/hosts/maya/plugins/publish/extract_handles.py, openpype/hosts/maya/plugins/publish/validate_frame_range.py
Move the Include/Exclude Handles Settings out of `ValidateFrameRange()` Plugin in a Custom Extractor.
=> Add Include Handles Extractor Publish Plugin

openpype/modules/deadline/common/publish/submit_publish_job.py, openpype/modules/deadline/max/publish/submit_max_deadline.py, openpype/modules/deadline/maya/publish/submit_maya_deadline.py, openpype/modules/deadline/nuke/publish/submit_nuke_deadline.py, openpype/pipeline/publish/lib.py
Update apply_settings() logic
Clean code which use apply_settings() mainly about Deadline module
=> Update apply_settings logic on filter_pyblish_plugins()

openpype/modules/ftrack/event_handlers_user/action_prepare_project.py
=> [HOTFIX] Fix Issue linked to checkbox attributes during Prepare Project Process

igniter/bootstrap_repos.py, igniter/tools.py, start.py
First concept of ability to pre-generate zip file from local instead of deadline workers.
=> [Enhancement] First concept of ability to pre-generate zip file from local instead of deadline workers.

openpype/hosts/blender/hooks/pre_add_install_custom_addons.py
Paragraphs contain detailed information on the changes made to the product or service, providing an in-depth description of the updates and enhancements. They can be used to explain the reasoning behind the changes, or to highlight the importance of the new features. Paragraphs can often include links to further information or support documentation.
Paragraphs of text giving context of additional technical information or code examples.
1. start with this step
2. follow this step
=> bugfix: add `as_posix` to passed path to avoid giving PosixPath

openpype/hosts/maya/api/pipeline.py, openpype/hosts/maya/api/workfile_template_builder.py, openpype/hosts/nuke/api/workfile_template_builder.py, openpype/pipeline/workfile/workfile_template_builder.py
Ajout du Panel "Maya Create" dans le "Workfile Placeholder Manager", permettant l'automatisation des créations d'Instance au moment du "Build Workfile From Template".
UI :
=> [Maya] Add " Maya Create" Panel in Maya Workfile Template Builder

openpype/lib/transcoding.py
Si l'on se refere a ce [ticket ](https://github.com/quadproduction/issues/issues/164), on peut s'apercevoir que oiio est extrêment lent car il traite les frames une par une sans aucune notion de parallèlisme, pour palier a ce problème, j'ai mis en place une solution de multithreading qui va venir traiter un chunk de frame par un nombre de thread logique disponible sur la machine qui éxécutera le code.
1. `git checkout enhancement/164-bug-publish-on-deadline-after-rendering`
2. Changer la version d'Openpype 
3. Aller sur une tâche de 'light' dans 'OP_TEST'
4. Lancer un rendu
=> [enhancement][farm] Add Multithreading to ExtractOIIOTranscode

openpype/hosts/maya/api/workfile_template_builder.py
Ajout d'un fix qui check l'exisence de l'element 'PLACEHOLDER_SET ' et corrige la fonction `post_placeholder_process(self, placeholder, failed)`.
=> [Maya][WorkfileTemplateBuilder] Add check PLACEHOLDER_SET exists

openpype/pipeline/workfile/workfile_template_builder.py
Revert "creator" attributes naming.
=> [HOTFIX] Fix Nuke Build Workfile Template

openpype/hosts/maya/api/workfile_template_builder.py, openpype/pipeline/workfile/workfile_template_builder.py
Ajout de la gestion des options de post_placeholder_process()/delete_placeholder() quand le placeholder ne contient pas de représentation.
=> [BuildWorkfileFromTemplate][Maya] Add post_placeholder_process when there is no representation

openpype/hosts/aftereffects/api/extension/index.html, openpype/hosts/aftereffects/api/launch_logic.py, openpype/hosts/aftereffects/api/lib.py, openpype/hosts/aftereffects/plugins/create/create_render.py, openpype/hosts/aftereffects/plugins/publish/collect_render.py, openpype/hosts/maya/api/plugin.py, openpype/hosts/maya/api/workfile_template_builder.py, openpype/hosts/nuke/api/lib.py, openpype/hosts/nuke/api/pipeline.py, openpype/hosts/tvpaint/lib.py, openpype/pipeline/workfile/workfile_template_builder.py, openpype/settings/entities/enum_entity.py, openpype/version.py
=> Release 3.16.9-quad-1.13.0

start.py
Set update_zxp_extensions() after configuring the OP environment settings in start.py.
=> Correct the execution order of update_zxp_extensions()

igniter/bootstrap_repos.py
=> Release/3.16.9 quad 1.16.1

openpype/modules/kitsu/plugins/publish/integrate_kitsu_review.py, openpype/version.py
- Bugfix: Fix Kitsu video review check, missing dot in extension
=> Release/3.16.9 quad 1.17.2
