- openpype/hosts/tvpaint/plugins/create/create_render.py
- openpype/hosts/tvpaint/plugins/create/create_review.py
- openpype/hosts/tvpaint/plugins/create/create_workfile.py
Add missing `enable` attribute set in internal tvPaint plugins. 
Linked issue : https://github.com/quadproduction/issues/issues/169
**This MR needs to be merge with this one : https://github.com/quadproduction/openpype-custom-plugins/pull/26** 
This is the attribute which seems to be checked by OpenPype to display the plugins in the publish window. Without it, disabling or enabling these in settings have no effect.
1. Update state of any tvPaint plugin
2. Launch tvPaint
3. With OpenPype, open the publish menu
> #169: bugfixe: add missing 'enabled' attribute to allow deactivation through settings

- openpype/hosts/tvpaint/plugins/create/create_render.py
Add toggle option for activating `Extract PSD` for render scene base subset.
**This MR needs to be merge with this one : https://github.com/quadproduction/openpype-custom-plugins/pull/31**
1. Open tvPaint
2. Launch a Scene render for any scene
3. Check for `.psd` file in publish folder.
> #198: enhancement: tvpaint - add extract_psd toggle button for scene render

- openpype/modules/ftrack/event_handlers_user/action_prepare_project.py
- openpype/modules/ftrack/ftrack_module.py
- openpype/settings/lib.py
When creating a new project on Ftrack, the OP attributes were not set with the Prepare Project action due to the protection of the anatomy settings. I added a check of the attributes: if there's new attribute to set, the protection is disabled.
1. create a new project on Ftrack
2. do the Prepare Project action on the new project
3. check if the attributes are correctly set
> Fix locked anatomy attributes for project creation

- openpype/hosts/maya/plugins/publish/validate_frame_range.py
- openpype/settings/entities/schemas/projects_schema/schema_project_maya.json
Add include/exclude handles settings during the ValidateFrameRange() process managed by Maya
1. `git checkout bugfix/209-bug-validate-frame-range-without-handles`
2. Check the task does not include handles in the settings, for example 'light' task
3. Open 'light' task in TEST_OP2_PUB_23_7 > 003 > 003_0010
4. As you see the light task contains handles in Ftrack
5. Select `Openpype > Publish` in the top bar menu
6. Publish has been sent with success in Deadline and publish job (659d814a1489900628ea7d6c
659d814a1489900628ea7d6d) will generate the sequence without handles.
> Add include/exclude handles to ValidateFrameRange process

- openpype/modules/deadline/common/publish/collect_pools.py
- openpype/modules/deadline/common/publish/submit_publish_job.py
This PR will add deadline pools to the publish and baking jobs when publishing "`use existing frames - far`m" in Nuke.
You can use this scene for testing purpose: Project: **LA_FIEVRE_P2_23_52,** Shot: **990_0020**, Task: **compo**
1. First, you should publish the two render jobs, select "`Farm Rendering`" as target and suspend publish jobs. This way you will have the frames needed for the next step. You can un check workfile publish. 
2. Once you have frames ready, you do a publish, but this time select "`use existing frame - farm`" as target. Leave review checked.
3. You should see the publish and baking jobs on deadline and they should have `fix` as pool.
> Add predefined pool for Nuke publish and prerender jobs

- openpype/modules/ftrack/event_handlers_server/event_keep_user_active_for_deadline.py
Implemented user reactivation to prevent publish job crashes when a Ftrack user with “**Active**” deadline jobs is deactivated.
Note that Active covers both **Queued** and **Rendering** Jobs. 
1. Checkout to this branch. 
2. Run a Ftrack Sync Server locally. Do not run it in parallel of the production sync server. 
3. Try to deactivate a user on Ftrack who has active jobs on deadline.
> Reactivating a Ftrack user with Active deadline jobs 

- openpype/modules/kitsu/utils/update_op_with_zou.py
Update Kitsu sync to also set the active test from all projects at sync launch.
1. Manipulate Kitsu productions
2. Launch sync (better to use a local mongodb by setting environment variable `OPENPYPE_MONGO`)
> #284: enhancement: synchronize project state at sync execution (before listening to events)

- openpype/lib/transcoding.py
- openpype/plugins/publish/extract_review.py
- openpype/plugins/publish/extract_review_slate.py
Resolved aspect ratio problem on review videos published on Ftrack.
This will not fix the thumbnail issue which is fixed in Openpype 3.17.7 here: https://github.com/ynput/OpenPype/commit/09b3646becdb77f2682a2aa8f148e3816bd58c95
1. As you should test it on the farm, the most simple way should be applying the modification of this PR to the code that locates here inside your home directory: ~/.local/share/openpype/[YOUR_OPENPYPE_VERSION]
2. you can delete checksums file if there is any error concerning this file.
3. publish this test scene (project: LA_FIEVRE_P2_23_52, Shots: 990_0020, task: compo) 
4. verify reviews on Ftrack.
> set correct aspect ratio for the review (quadproduction/issues#255)

- openpype/hosts/blender/hooks/pre_add_set_scene_properties.py
Directly retrieve hierarchy_data instead of parsing shot_name to retrieve correct informations and avoid crash when opening assets files with Blender.
Fix quadproduction/issues#312
1. Open any asset Blender file
2. See that it works well
> #312: bugfix: also handle assets workfiles in pre_add_set_scene_properties hook

- openpype/hosts/tvpaint/plugins/publish/help/validate_start_frame.xml
- openpype/hosts/tvpaint/plugins/publish/validate_start_frame.py
- openpype/settings/defaults/project_settings/tvpaint.json
- openpype/settings/entities/schemas/projects_schema/schema_project_tvpaint.json
- server_addon/tvpaint/server/settings/publish_plugins.py
Add custom frame input in validate  start frame tvPaint validator.
Extract PSD has been updated to update outputs psd names according to the given start frame, which can now have other values than 0.
Link to the PR : https://github.com/quadproduction/openpype-custom-plugins/pull/33
Fix quadproduction/issues#300
1. Open any tvPaint scene
2. Launch scene render, with or without the correct start frame
> #300: enhancement: add custom start frame for tvpaint start frame validator

- openpype/hosts/nuke/api/pipeline.py
- openpype/hosts/openrv/plugins/publish/extract_annotations.py
Ftrack request was too soft to identify the correct asset in ftrack database, I've added project_ftrack_id, asset_parent_name parameters in the request, this fix the issue linked to this [ticket](https://github.com/quadproduction/issues/issues/222).
I also added a check in order the open_rv app will be none blockable during the nuke launcher.
1. In Ftrack, go to MISKINA_S02_23_19 > Shots > 201 > 201_106
2. Click on Open wih RV
3. Draw an annotation ('F10' shortcu) 
4. Publish
5. Go in Ftrack, and you should see your annotation
6. Delete your annotation
> Add more filters to ftrack query which identify asset where publish the annotation

- openpype/lib/__init__.py
- openpype/lib/transcoding.py
- openpype/plugins/publish/extract_thumbnail.py
Fixed thumbnail aspect ratio.
These modifications come from OpenPype 3.17.7
1. As you should test it on the farm, the most simple way should be applying the modification of this PR to the code that locates here inside your home directory: `~/.local/share/openpype/[YOUR_OPENPYPE_VERSION]`
2. you can delete checksums file if there is any error concerning this file.
3. publish this test scene (project: LA_FIEVRE_P2_23_52, Shots: 990_0020, task: compo)
4. verify thumbnails on Ftrack.
> Fix thumbnail aspect ratio (quadproduction/issues#255)

- openpype/hosts/maya/api/lib.py
This fix Rolex look export and assignment problems. 
1. Try to export a look from this scene: project: RLX_NOVELTIES_2024_23_62 -> WATCHES -> SKY_DWELLER -> M336935_0004 -> reference -> M336935_0004_reference_v005.ma
2. Then open an empty scene here : RLX_NOVELTIES_2024_23_62 -> 800 -> 800_0060 -> animation
3. load the point cache and apply the exported look via Look Manager.
> Fix Rolex look export and assign problems

- openpype/client/mongo/operations.py
- openpype/modules/ftrack/event_handlers_user/action_prepare_project.py
The issue is the "bypass_protect_anatomy_attributes" arguments was setted too late, so when the Prepare Project Action execute this [create_project(project_name, project_code)](https://github.com/quadproduction/OpenPype/blob/f17e221e4b0601598abe8e90a6d7a3e2334616dd/openpype/modules/ftrack/event_handlers_user/action_prepare_project.py#L399C13-L399C27), it actually calls the mongo client [create_project()
](https://github.com/quadproduction/OpenPype/blob/f17e221e4b0601598abe8e90a6d7a3e2334616dd/openpype/client/mongo/operations.py#L545) which actually save project settings, but as at this point the "bypass_protect_anatomy_attributes" was not setted, that's explain why it was not possible to write any data in ftrack.
1. Create a new project on Ftrack
2. Do the Prepare Project action on the …
> Fix Prepare Project

- openpype/plugins/publish/collect_sequence_frame_data.py
Fix quadproduction/issues#333
Change the method to retrieve the fps info to avoid blocking collect step while publishing sequence image with the standalone.
1. Open the standAlone publisher
2. Create a publish for a render by dropping a sequence of image in the correct window
3. publish it
> #333: bugfix: changement de la recup de valeur fps des settings

- openpype/hosts/maya/plugins/publish/validate_look_sets.py
- openpype/settings/defaults/project_settings/maya.json
- openpype/settings/entities/schemas/projects_schema/schemas/schema_maya_publish.json
Excluded user-defined sets with pre-defined suffixes from collected look sets
1. Run the code in the development environment (opdev). Add a custom suffix (for example, `RLX`) to the project settings for the RLX_NOVELTIES_2024_23_62 project located at `project_settings/maya/publish/ValidateLookSets/exclude_sets_with_suffix/`.
2. Open this scene: Project: RLX_NOVELTIES_2024_23_62 -> WATCHES -> SKY_DWELLER -> M336935_0004 -> Reference -> M336935_0004_reference_v005.ma.
3. Check if there are sets created by the user. There is already one named setBordVerre_RLX.
4. Open the publish interface and validate. (To verify everything is correct, you can remove `RLX` from the end of the set name and retry the validation process.)
> Excluded sets with pre-defined suffixes from collected look sets

- openpype/modules/deadline/utils.py
- website/docs/module_deadline.md
I added a "workfile" key in the possible keys of the template for the deadline batch name and job name. The "workfile" key corresponds to the name of the current workfile without the extension.
1. go in the deadline batch name and job name settings
2. add the "workfile" key in the template
3. send a job to deadline
4. go to your job in deadline and see the workfile name in the batch name or job name
> Enhancement: be able to use the workfile name in the template of the deadline job name and batch name

- openpype/hosts/maya/api/lib.py
- openpype/hosts/maya/plugins/load/load_reference.py
Add the possibility to add an "active" argument type bool to activate or deactivate an animation instance at creation with the workfile template builder.
1. go in the desired placeholder creation interface
2. in the "Loader Arguments" entry, add `"active":False`
3. go in an empty scene and start the "Build Workfile from template"
4. select your animation instance and see that it is deactivate
> Enhancement: possibility to deactivate animation instance at creation with workfile template builder

- openpype/hosts/hiero/api/startup/Python/StartupUI/add_resolve_entries.py
Add the add_resolve_entries.py script to Hiero that adds new variables "height" and "width" to the exports path in Hiero.
1. open the export window in Hiero
2. hover the shot in the "Export Structure" module
3. check if "height" and "width" are in the available variables
> Enhancement: add an old script from shotgun pipeline for Hiero

- openpype/modules/ftrack/__init__.py
- openpype/modules/ftrack/plugins/publish/integrate_ftrack_description.py
- openpype/modules/ftrack/plugins/publish/integrate_ftrack_source_workfile.py
- openpype/modules/ftrack/utils.py
This PR is here to fix this feature. Sometimes the AssetVersion data are not in the instance, so we have to do a query to ftrack in order to get the latest AssetVersion for the current asset.
> Auto comment on version with the source workfile in it

- openpype/hosts/maya/plugins/publish/collect_render.py
When renaming a layer, rename also the renderlayer instance in the outliner when collecting the render layers.
1. create an animation instance
2. rename the associated layer
3. click the validate button in the publisher
4. the render instance in the outliner is renamed
> Bugfix: rename renderlayer instance if the layer name is changed

- openpype/modules/sync_server/providers/sftp.py
Update code to use getter instead of direct access when retrieving SFTP informations for Wizz.
fix quadproduction/issues#341
OpenPype was trying to initialize sftp before having the necessary informations. By doing so, it completely broke the SFTPHandler. By checking if the correct value is initialized, the SFTPHandler get correctly updated after.
1. Open the loader
2. Download any file
3. Check Sync queue
> #341: bugfix: use get instead of direct access when retrieving ftp data

- openpype/tools/workfile_template_build/window.py
Set an empty dict by default for the actions instead of returning None to avoid errors when creating placeholder (None value is not supported by the EnumDef class)
1. open Nuke
2. go in Openpype menu > Template Builder > Create Placeholder
3. create a placeholder with `Nuke load` plugin
4. check that the info in the placeholder are correct
> Bugfix: set default empty dict for actions in create placeholder manager

- openpype/modules/deadline/deadline_module.py
- openpype/modules/deadline/utils.py
- openpype/settings/entities/enum_entity.py
As mentionned in this [ticket](https://github.com/quadproduction/issues/issues/341), in case the deadline's url is wrong, it automaticaly raise an Error cause of an [ConnectionError](https://github.com/quadproduction/OpenPype/blob/851b14bde3067c81c3acbca21550f5d27d32de1f/openpype/modules/deadline/deadline_module.py#L121).
I've fixed it by added a pre request which act like a ping on the deadline's url. This will detect if we can get the datas from Deadline API REST, or not. If not, values are automaticaly setted as None.
This fix make also the settings non blocking.
> Fix blocking issue on Deadline EnumEntities

- openpype/hosts/maya/plugins/publish/collect_handles.py
Fix issue linked to the execution Order during publish step
Replace ExtractHandles (Extractor Plugin) by CollectHandles (Collector Plugin).
> Fix Execution Order for CollectHandles plugin

- openpype/hosts/blender/plugins/publish/collect_instances.py
Return empty list when retrieving registered instances.
Fix quadproduction/issues#321
Allow to publish workfile or use validate on scene which doesn't have subset instances.
1. Open any empty scene
2. Try to validate or to publish workfile
> #321: update: return empty list when OpenPype can't retrieve registered instances

- openpype/modules/kitsu/plugins/publish/integrate_kitsu_review.py
- openpype/settings/defaults/project_settings/kitsu.json
- openpype/settings/entities/schemas/projects_schema/schema_project_kitsu.json
Add option in settings to enable and to activate normalization for kitsu review integration.
The modification is designed to also work without these informations in settings.
1. Launch any soft which upload a render on Kitsu
2. Check the uploaded file on Kitsu and check for video ratio / size
> #364: enhancement: add normalize option for kitsu review integration

- openpype/pipeline/workfile/workfile_template_builder.py
La méthode `cleanup_placeholder()` est l'ancien nom de la méthode `delete_placeholder()`.
Elle nécessite d'être supprimé.
> [Nuke][WorkfileTemplateBuilder] Clean Useless Code 

- openpype/hosts/blender/blender_addon/addons/RenderPlayblast.py
Set container option after selecting format for output type.  By default, it was using a container which wasn't  corresponding to `.mp4` extension.
1. Open any Blender scene
2. Launch playblast
3. Try to import rendered video in After Effects
> #386: bugfix: set container option after selecting output type

- openpype/lib/transcoding.py
- openpype/settings/defaults/project_settings/global.json
- server_addon/core/server/settings/publish_plugins.py
- website/docs/pype2/admin_presets_plugins.md
Suppression des flags '-intra' étant 'deprecated' depuis notre passage a ffmpeg 6.1-static
> Remove -intra hardcoded flags for ffmpeg processing

- openpype/pipeline/workfile/workfile_template_builder.py
Ignore la création du context_filter lorsque nous sommes en situation d'un template 'linked_asset' et dont la liste est vide dans Ftrack.
Auquel cas, il générait une regex vide dans le context_filter qui venait charger tout les assets disponibles.
> [Maya][WorkfileTemplateBuilder] Ignore contex_filter creation when linked_asset are none

- openpype/hosts/maya/api/plugin.py
Fix the error by returning the correct renamed node.
1. create a renderlayer instance
2. rename the layer in the maya render setup editor
3. open the publish window
4. there's shouldn't be any error
5. the Renderlayer, Subset, and Variant extra attribute should be updated
> Fix: error when opening the publish window if a renderlayer has been renamed

- openpype/hosts/nuke/api/workfile_template_builder.py
- openpype/pipeline/workfile/workfile_template_builder.py
Déploiement d'un fix permettant la lecture des anciens plugins 'Creator' au moment du Build, cependant la création n'autorise désormais que la création des nouveaux plugins càd du type 'Create'.
La transition se fera ainsi dans le temps sans impacter les anciennes prods ni les nouvelles.
> [Nuke][BuildTemplateFromWorkfile] Allows Transition between legacy creators and new one

- openpype/hosts/photoshop/api/extension/client/client.js
- openpype/hosts/photoshop/api/extension/host/index.jsx
- openpype/hosts/photoshop/api/ws_stub.py
Fix quadproduction/issues#521
Ajout d'une fonction pour recupérer les dimensions du doc actif et une autre pour crop tous les layers selon des coordonées
> 521: enhancement: Cropper tous les layers à la taille du canva lors d'un publish

- igniter/__init__.py
- igniter/bootstrap_repos.py
- openpype/modules/update_zxp_extensions_action.py
- pyproject.toml
- start.py
- Add the posibility to ignore zxp update with this flag `--zxp-ignore-update`
- Replace ExManCmd by Extract Zxp into AppData User (Automatically detected by Adobe and does not need admin right)
- Fix QApplication instance already running when zxp windows are crashing
> Replace ExManCmd by Zxp Extractor & Add --zxp-ignore-update Flag
